name: CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hey_professor
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: hey_professor
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    - name: Installing Package.json
      run: npm install

    - name: Build Assets
      run: npm run build
        
    - name: Execute tests (Unit and Feature tests) via PEST
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: hey_professor
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test --parallel
      
    - name: Execute Larastan
      run: vendor/bin/phpstan analyse
      
    - name: Execute Laravel Pint
      run: vendor/bin/pint --test

